### ISSUE TITLE
raspberry error test_backend.py TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by luisrodriguezgonzalez** [kivy-garden/garden.matplotlib#45]
pi@raspberrypi:~/garden.matplotlib/examples $ python test_backend.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_16-12-20_1.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "test_backend.py", line 140, in <module>
     MatplotlibTest().run()
   File "/home/pi/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/pi/kivy/kivy/base.py", line 500, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 90, in mainloop
     self._mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 85, in _mainloop
     EventLoop.idle()
   File "/home/pi/kivy/kivy/base.py", line 336, in idle
     Clock.tick()
   File "/home/pi/kivy/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 368, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7740)
   File "kivy/_clock.pyx", line 398, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7617)
   File "kivy/_clock.pyx", line 396, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7538)
   File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3530)
   File "/home/pi/kivy/kivy/uix/boxlayout.py", line 311, in do_layout
     c.size = (w, h)
   File "kivy/properties.pyx", line 423, in kivy.properties.Property.__set__ (kivy/properties.c:5572)
   File "kivy/properties.pyx", line 1295, in kivy.properties.ReferenceListProperty.set (kivy/properties.c:21379)
   File "kivy/properties.pyx", line 516, in kivy.properties.Property.dispatch (kivy/properties.c:7105)
   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:14035)
   File "kivy/_event.pyx", line 1131, in kivy._event.EventObservers._dispatch (kivy/_event.c:13193)
   File "/home/pi/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py", line 1179, in _on_size_changed
     self.figure.set_size_inches(winch, hinch)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc1_2788.g424d3b0-py2.7-linux-armv7l.egg/matplotlib/figure.py", line 720, in set_size_inches
     manager.resize(int(canvasw), int(canvash))
   File "/home/pi/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py", line 1247, in resize
     Window.size(w, h)
 TypeError: 'tuple' object is not callable

**Comment by luisrodriguezgonzalez** [comment]
Solved in
[https://github.com/kivy/kivy/issues/4831](url)

**Comment by luisrodriguezgonzalez** [comment]
dessant , thank you very much
