### ISSUE TITLE
matplotlib/_path.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by NaniteFactory** [kivy-garden/garden.matplotlib#53]
buildozer version: 0.33
I edited `buildozer.spec` only by adding `requirements = kivy, python2, matplotlib, numpy, dateutil, pytz, pyparsing, six, pillow, cycler` and everything else set by default.

I'm trying to build `test_plt.py` example with buildozer. `bulidozer android debug` does build an apk package, but when running the app it keeps crashing with following adb logcat messages.
Could someone please help, thank you.

```
I/python  (27633): ('Android kivy bootstrap done. __name__ is', '__main__')
I/python  (27633): ['/data/data/org.test.myapp/files/app/lib/python2.7/site-packages', '/data/data/org.test.myapp/files/app/lib/site-python']
I/python  (27633): AND: Ran string
I/python  (27633): Run user program, change dir and execute entrypoint
I/python  (27633): [WARNING] [Config      ] Older configuration version detected (0 instead of 19)
I/python  (27633): [WARNING] [Config      ] Upgrading configuration in progress.
I/python  (27633): [INFO   ] [Logger      ] Record log in /data/data/org.test.myapp/files/app/.kivy/logs/kivy_17-05-31_0.txt
I/python  (27633): [INFO   ] [Kivy        ] v1.10.0
I/python  (27633): [INFO   ] [Python      ] v2.7.2 (default, May 30 2017, 23:39:33) 
I/python  (27633): [GCC 4.8]
I/python  (27633):  Traceback (most recent call last):
I/python  (27633):    File "/home/user/hi/.buildozer/android/app/main.py", line 8, in <module>
I/python  (27633):    File "/home/user/hi/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/garden/__init__.py", line 100, in load_module
I/python  (27633):    File "/home/user/hi/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/garden/__init__.py", line 104, in _load_module
I/python  (27633):    File "/home/user/hi/.buildozer/android/app/libs/garden/garden.matplotlib/__init__.py", line 1, in <module>
I/python  (27633):    File "/home/user/hi/.buildozer/android/app/libs/garden/garden.matplotlib/backend_kivy.py", line 245, in <module>
I/python  (27633):    File "/home/user/hi/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/matplotlib/transforms.py", line 39, in <module>
I/python  (27633):  ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/lib/python2.7/site-packages/matplotlib/_path.so" is 64-bit instead of 32-bit
I/python  (27633): Python for android ended.
V/SDL     (27633): onPause()
V/SDL     (27633): nativePause()
V/SDL     (27633): onWindowFocusChanged(): false
V/SDL     (27633): surfaceDestroyed()
V/SDL     (27633): onDestroy()
I/art     (27633): System.exit called, status: 0
I/AndroidRuntime(27633): VM exiting with result code 0, cleanup skipped.
```

**Comment by matham** [comment]
This is a buildozer or py4a issue and not a garden.matplotlib issue so you should open a issue there because no one watching this is likely to be able to help. Or even better, this seems like a support question so try asking on the kivy-users list or on IRC.
