### ISSUE TITLE
Problem whit from kivy.garden.matplotlib.backend_kivyagg import FigureCanvasKivyAgg on windows

### ISSUE THREAD

**Issue by juanjpnv** [kivy-garden/garden.matplotlib#61]
When I import the garden.matplotlib package i recive a error mensage:
ImportError: cannot import name 'weight_as_number' from 'matplotlib.font_manager'

I used the Python in the Command Prompt to import step-by-step. I find a error in the garden.matplotlib import line.

System: Windows 10, Python 3.7.0, Kivy 1.10.1

`>>> import matplotlib`
Backend TkAgg is interactive backend. Turning interactive mode on.

`>>> matplotlib.use('module://kivy.garden.matplotlib.backend_kivy')`

`>>>from kivy.garden.matplotlib.backend_kivyagg import FigureCanvasKivyAgg`
[INFO   ] [Logger      ] Record log in C:\Users\user\.kivy\logs\kivy_18-10-03_7.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
 Traceback (most recent call last):
   File "<input>", line 1, in <module>
   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
     module = self._system_import(name, *args, **kwargs)
   File "D:\Documents\venv\lib\site-packages\kivy\garden\__init__.py", line 100, in load_module
     return self._load_module(fullname, moddir)
   File "D:\Documents\venv\lib\site-packages\kivy\garden\__init__.py", line 104, in _load_module
     ('', '', imp.PKG_DIRECTORY))
   File "C:\Python37-32\lib\imp.py", line 245, in load_module
     return load_package(name, filename)
   File "C:\Python37-32\lib\imp.py", line 217, in load_package
     return _load(spec)
   File "C:\Users\user\.kivy\garden\garden.matplotlib\__init__.py", line 1, in <module>
     from kivy.garden.matplotlib.backend_kivy import FigureCanvasKivy,\
   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
     module = self._system_import(name, *args, **kwargs)
   File "C:\Users\user\.kivy\garden\garden.matplotlib\backend_kivy.py", line 257, in <module>
     from matplotlib.font_manager import weight_as_number
 ImportError: cannot import name 'weight_as_number' from 'matplotlib.font_manager' (D:\Documents\venv\lib\site-packages\matplotlib\font_manager.py)

**Comment by xstreck1** [comment]
Hi, I had the same issue. This is due to incompatibility with matplotlib 3.0.0+ . 

I've created a fork that fixes the issue and requested a pull.

In the meantime you can either get the new source here: https://github.com/xstreck1/garden.matplotlib or downgrade matplotlib to 2.2.2 .

**Comment by matham** [comment]
Fixed by https://github.com/kivy-garden/garden.matplotlib/pull/62.

**Comment by juanjpnv** [comment]
I downgrade matplotlib to 2.2.2 and it's solved.
Thanks
