### ISSUE TITLE
test_backend.py - KeyError: 'kivy.garden.matplotlib'` line 640, in _load_backward_compatible

### ISSUE THREAD

**Issue by pidou46** [kivy-garden/garden.matplotlib#73]
Windows10
Python 3.7.9
Kivy 2.0.0
matplotlib 3.4.2

` %Run test_backend.py toto.txt test.py
[INFO   ] [Logger      ] Record log in F:\users\slestang\.kivy\logs\kivy_21-06-07_1.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "F:\users\slestang\AppData\Roaming\Python\Python37\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "F:\users\slestang\AppData\Local\Programs\Thonny\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil (img_sdl2, img_ffpyplayer ignored)
Traceback (most recent call last):
  File "F:\users\slestang\Downloads\kivy_matplotlib_demo2.py", line 8, in <module>
    from kivy.garden.matplotlib.backend_kivyagg import FigureCanvas,\
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 640, in _load_backward_compatible
KeyError: 'kivy.garden.matplotlib'`

**Comment by pidou46** [comment]
Sorry have not installed it correctly  with :
garden install matplotlib
