### ISSUE TITLE
Unable to install garden.matplotlib in windows

### ISSUE THREAD

**Issue by ajugeorge97** [kivy-garden/garden.matplotlib#74]
Hi,

i was trying to install garden matplotlib in windows but it failing

`C:\Users\AJU\AppData\Local\Programs\Python\Python39\Scripts>python garden install matplotlib
Downloading http://github.com/kivy-garden/garden.matplotlib/archive/master.zip ...
Progression 1024 |
Progression 2048 /
Progression 3072 -
Progression 4096 \
Progression 5120 |
Progression 6144 /
Progression 7168 -
Progression 8192 \
Progression 9216 |
Progression 10240 /
Progression 11264 -
Progression 12012 \
Download done (12012 downloaded)
Extracting...
Cleaning...
Traceback (most recent call last):
  File "C:\Users\AJU\AppData\Local\Programs\Python\Python39\Scripts\garden", line 223, in <module>
    GardenTool().main(sys.argv[1:])
  File "C:\Users\AJU\AppData\Local\Programs\Python\Python39\Scripts\garden", line 84, in main
    options.func()
  File "C:\Users\AJU\AppData\Local\Programs\Python\Python39\Scripts\garden", line 143, in cmd_install
    self.extract(fd, tempdir)
  File "C:\Users\AJU\AppData\Local\Programs\Python\Python39\Scripts\garden", line 214, in extract
    z = zipfile.ZipFile(fd)
  File "C:\Users\AJU\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Users\AJU\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by Joshua-Douglas** [comment]
For what it's worth I just successfully installed `garden.matplotlib` using `garden install garden.matplotlib`. I noticed you posted a similar bug on the `garden` repo related to the `graph` flower. It seems like this is either a bug in `garden`, or an issue with your environment. 

Did you ever resolve this issue? I'd start by uninstalling and reinstalling `kivy` and `garden`, and reinstalling using a clean `venv`. In either case the current release zip file is a valid `zip` file, so I don't think this bug belongs in this repo. 

My vote is to close this issue.

Here is my recent install log:
```
Downloading https://github.com/kivy-garden/garden.matplotlib/archive/master.zip ...
Progression 1024 | 
Progression 2048 /
Progression 3072 -
Progression 4096 \
Progression 5120 |
Progression 6144 /
Progression 7168 -
Progression 8192 \
Progression 9216 |
Progression 10240 /
Progression 11264 -
Progression 12288 \
Progression 13312 |
Progression 14336 /
Progression 15360 -
Progression 16384 \
Progression 17408 |
Progression 18432 /
Progression 19456 -
Progression 20480 \
Progression 21297 |
Download done (21297 downloaded)
Extracting...
Installing new version...
Done! garden.matplotlib is installed at: C:\Users\joshu\.kivy\garden\garden.matplotlib
Cleaning...
```
