### ISSUE TITLE
potential issue with matplotlib 3.8.0

### ISSUE THREAD

**Issue by tcaduser** [kivy-garden/garden.matplotlib#80]
When trying my app on macos:

```
 Traceback (most recent call last):
   File "/Users/jsanchez/git/tcadapp/matplotlib/main.py", line 150, in <module>
     MainApp().run()
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/Users/jsanchez/git/toolchain_build/lib/python3.9/site-packages/kivy/uix/boxlayout.py", line 323, in do_layout
     c.size = (w, h)
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 1478, in kivy.properties.ReferenceListProperty.set
   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "/Users/jsanchez/.kivy/garden/garden.matplotlib/backend_kivy.py", line 1233, in _on_size_changed
     self.resize_event()
 AttributeError: 'FigureCanvasKivyAgg' object has no attribute 'resize_event'
```

downgrading to python 3.7.2 fixes the problem:
```
% pip install --upgrade matplotlib==3.7.2
```

**Comment by tcaduser** [comment]
It look like there were some API changes affecting resize_event:
https://matplotlib.org/3.8.0/api/prev_api_changes/api_changes_3.8.0.html
