### ISSUE TITLE
ModuleNotFoundError: No module named 'kivy.garden.matplotlib.backend_kivyagg'

### ISSUE THREAD

**Issue by Patricklevyy** [kivy-garden/garden.matplotlib#83]
Hello, is there any incompatibility between a kivy garden matplotlib and pyinstaller? I have a kivy application that uses the module kivy.garden.matplotlib.backend_kivyagg. When I test my program it works fine but once converted into an executable (.exe) I get this error below. I'm using a virtual environment and I've checked that the module is correctly installed. I also run the pyinstaller command in the same viral environment.
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "myapp\load_data_app.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "myapp\curve_drawing.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivy.garden.matplotlib.backend_kivyagg'

```
I use:
```
Kivy==2.2.1
Kivy-Garden==0.1.5
kivy-garden.graph==0.4.0
kivy-matplotlib-widget==0.6.1
kivymd==1.1.1
matplotlib==3.7.2
pyinstaller==5.6.2
```
Thank you for your help.

**Comment by mp-007** [comment]
kivyagg is for kivy-garden matplotlib library and it's not install in your environnement. kivy-matplotlib-widget is an other library and you don't need to import kivy.garden.matplotlib.backend_kivyagg with this library.

**Comment by tcaduser** [comment]
There are 2 kivy matplotlib garden flowers:

There is the legacy:
https://github.com/kivy-garden/garden.matplotlib

and the new:
https://github.com/kivy-garden/matplotlib

which is still being migrated to the new installation methods, which is
supposed to be very easy.

I have only been using the legacy, which requires the garden command.

One thing to note when you get this all working,  neither garden flower
will work with matplotlib 3.8.0, and you would need to install a lower
version like matplotlib 3.7.2.

For me to install to using the legacy flower:
chmod +x $VIRTUAL_ENV/bin/garden
garden install matplotlib --app

which required me to make sure the garden command was executable.  The
"--app" option is necessary to do a proper install in your source directory.


Regards,

Juan

**Comment by Patricklevyy** [comment]
Thanks, I found the solution, I was using an old version of pyinstaller and also a bad command line to do it.
